import {BsFillMoonStarsFill} from "react-icons/bs"
import Head from 'next/head'
import {AiFillFacebook, AiFillGithub, AiFillTwitterCircle} from "react-icons/ai"
import Image from "next/image"
import wave from "../public/dev-ed-wave.png"
import pic from "../public/design.png"
import anotherPic from "../public/code.png"
import consult from "../public/consulting.png"
import port1 from "../public/web1.png"
import port2 from "../public/web2.png"
import port3 from "../public/web3.png"
import port4 from "../public/web4.png"
import port5 from "../public/web5.png"
import port6 from "../public/web6.png"
import { useState } from "react"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:p-50 dark:bg-gray-900 dark:text-white">
        <section className='min-h-screen'>
          <nav className="py-10 flex justify-between mb-4">
            <h1 className="text-2xl font-burtons">bensla</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="text-xl cursor-pointer"/>
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 rounded-md ml-7 text-white' href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className=" text-4xl text-teal-500 font-medium">Ben Ken Idehen</h2>
            <h3 className="font-medium text-2xl py-2">Full stack web Developer.</h3>
            <p className="leading-8 text-gray-700">A freelancer providing services to everyone out there looking for <br />a web developer join me and we could make a great team.</p>
          </div>
          <div className="flex text-gray-700 gap-16 text-5xl justify-center mb-7">
            <AiFillFacebook />
            <AiFillGithub />
            <AiFillTwitterCircle />
          </div>
          <div className=" bg-gradient-to-b  from-teal-500 m-auto rounded-full w-80 h-80 flex justify-center overflow-hidden mt-20 relative">
            <Image src={wave} layout="fill" objectFit="cover" className="my-auto"/>
          </div>
        </section>
        <section>
          <div className="m-0 lg:text-center py-1">
            <h3 className="text-3xl p-2">Services I offer</h3>
            <p className="text-md text-gray-800 leading-8">
              Since I started developing I have worked for <span className=" text-teal-400">Techskol</span> and I have done remote work for some startup <span className="text-teal-400">companies</span> 
            </p>
          </div>
          <div className="lg:flex gap-20">
            <div className="text-center shadow-lg rounded-lg pt-10 p-6 py-10 mb-3 mt-3 flex flex-col">
              <Image src={pic} width={100} height={100} className="mx-auto"/>
              <div>
                <h3 className="pt-8 font-medium text-2xl py-3">Beautiful Web Designs</h3>
                <p className="py-2">
                  I create elegant web designs with a pure sense of art
                </p>
                <h4 className="text-xl py-2 text-teal-600">Tools I use</h4>
                <p className="py-1 text-gray-800">Intellij IDEA</p>
                <p className="py-1 text-gray-800">Vs Code</p>
                <p className="py-1 text-gray-800">Canva</p>
              </div>
            </div>
            <div className="text-center shadow-lg rounded-lg pt-10 p-6 py-10 mb-3 mt-3 flex flex-col">
              <Image src={anotherPic} width={100} height={100} className="mx-auto"/>
              <div>
                <h3 className="pt-8 font-medium text-2xl py-3">Full stack engineer (PHP MYSQL FRONT-END)</h3>
                <p className="py-2">
                  Work with and we can take web development to another level
                </p>
                <h4 className="text-xl py-2 text-teal-600">Tools I use</h4>
                <p className="py-1 text-gray-800">Intellij IDEA</p>
                <p className="py-1 text-gray-800">Vs Code</p>
                <p className="py-1 text-gray-800">Php Storm</p>
              </div>
            </div>
            <div className="text-center shadow-lg rounded-lg pt-10 p-6 py-10 mb-3 mt-3 flex flex-col">
              <Image src={consult} width={100} height={100} className="mx-auto"/>
              <div>
                <h3 className="pt-8 font-medium text-2xl py-3">Code consultant</h3>
                <p className="py-2">
                  Together we could solve all the problems we have when we code
                </p>
                <h4 className="text-xl py-2 text-teal-600">Tools I use</h4>
                <p className="py-1 text-gray-800">Intellij IDEA</p>
                <p className="py-1 text-gray-800">Vs Code</p>
                <p className="py-1 text-gray-800">Canva</p>
              </div>
            </div>
          </div>
          <div>
            <h3 className="text-2xl py-5">Portofolio</h3>
            <p className="text-gray-800">
              This is a bunch of my work be sure to check out <span className="text-teal-600">Github</span> repo on <span className="text-teal-600">github.com/Ben-chanan008</span>
            </p>
            <p className="leading-8">
              Please check out if you like check out more on the github repo
            </p>
            <div className="mb-2 lg:flex gap-10 py-10 flex-wrap flex-col">
              <div className="mb-2 basis-1/3 flex-1">
                <Image src={port1} className="object-cover rounded-lg" width={'100%'} height={'100%'} layout="responsive"/>
              </div>
              <div className="mb-2 basis-1/3 flex-1">
                <Image src={port2} className="object-cover rounded-lg" width={'100%'} height={'100%'} layout="responsive"/>
              </div>
              <div className="mb-2">
                <Image src={port3} className="object-cover rounded-lg" width={'100%'} height={'100%'} layout="responsive"/>
              </div>
              <div className="mb-2 basis-1/3 flex-1">
                <Image src={port4} className="object-cover rounded-lg" width={'100%'} height={'100%'} layout="responsive"/>
              </div>
              <div className="mb-2 basis-1/3 flex-1">
                <Image src={port5} className="object-cover rounded-lg" width={'100%'} height={'100%'} layout="responsive"/>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
